# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: incident_data.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13incident_data.proto\"\xf8\x01\n\x0cIncidentData\x12\x13\n\x0bincident_id\x18\x01 \x01(\x03\x12\x14\n\x0cinventory_id\x18\x02 \x01(\x03\x12\x15\n\rincident_type\x18\x03 \x01(\t\x12\x14\n\x0cservice_type\x18\x04 \x01(\t\x12\x10\n\x08severity\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x15\n\ropen_datetime\x18\x07 \x01(\x03\x12\x16\n\x0e\x63lose_datetime\x18\x08 \x01(\x03\x12\x16\n\x0eincident_owner\x18\t \x01(\t\x12\x11\n\tupdate_at\x18\n \x01(\x03\x12\x14\n\x0c_CHANGE_TYPE\x18\x0b \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'incident_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INCIDENTDATA']._serialized_start=24
  _globals['_INCIDENTDATA']._serialized_end=272
# @@protoc_insertion_point(module_scope)
