# Generated by Django 4.2.9 on 2024-01-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETLTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_datetime', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=255)),
                ('no_rows', models.IntegerField()),
                ('is_consistent', models.IntegerField()),
                ('is_complete', models.IntegerField()),
            ],
            options={
                'db_table': 'etl_transaction',
                'ordering': ['-id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'view_source',
                'ordering': ['id'],
                'managed': False,
            },
        ),
    ]
